// Autogenerated-style Firebase options file.
// Recommended: run `flutterfire configure` to generate correct values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzaBeS_2om0I2C8V-UR6hOsJpyxY5srI',
    appId: '1:880715701828:web:7b87367abf1e1b1879e611',
    messagingSenderId: '880715701828',
    projectId: 'eclassiut',
    authDomain: 'eclassiut.firebaseapp.com',
    storageBucket: 'eclassiut.firebasestorage.app',
    measurementId: 'G-BX1RTF4X8K',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web in this repository. '
      'For Android/iOS, use the platform config files or run flutterfire configure.',
    );
  }

  static bool get isPlaceholder {
    return web.apiKey == 'REPLACE_ME' ||
        web.appId == 'REPLACE_ME' ||
        web.messagingSenderId == 'REPLACE_ME' ||
        web.projectId == 'REPLACE_ME';
  }
}
